apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-x86
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-x86
  template:
    metadata:
      labels:
        app: nginx-x86
    spec:
      nodeSelector:
        group: x86
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "x86"
          effect: "NoSchedule"
      containers:
      - name: nginx
        image: nginx