apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-spot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-spot
  template:
    metadata:
      labels:
        app: nginx-spot
    spec:
      nodeSelector:
        group: spot
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      containers:
      - name: nginx
        image: nginx
