apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-arm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-arm
  template:
    metadata:
      labels:
        app: nginx-arm
    spec:
      nodeSelector:
        group: arm
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "arm"
          effect: "NoSchedule"
      containers:
      - name: nginx
        image: nginx