apiVersion: v2
name: karpenter-resources
description: A Helm chart to deploy karpenter-resources
maintainers:
- name: Moushegh Amirbekyan
  email: mousheghamirbekyan@gmail.com

type: application
version: 1.8.2
appVersion: 1.8.2
